### ISSUE TITLE
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by bmaltais** [7eu7d7/DreamArtist-sd-webui-extension#1]
Tried running a training session following the example on the site but I keep getting this error.

Tried launching webui with --no-half option but does not change anything.

Any idea?

```
Training at rate of 0.003 until step 100000
Preparing dataset...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.80it/s]
  0%|                                                                                                                                   | 0/100000 [00:00<?, ?it/s]
Applying xformers cross attention optimization.
Error completing request
Arguments: ('test-jungho_lee', '0.003', 1, 'D:\\dreambooth\\train_jungho_lee\\portrait-pp', 'textual_inversion', 512, 640, 100000, 500, 500, 'D:\\stable-diffusion-webui\\textual_inversion_templates\\style.txt', True, False, '', '', 20, 1, 7, -1.0, 448, 640, 5.0, '', True, True, 1, 1) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\DreamArtist\scripts\dream_artist\ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "D:\stable-diffusion-webui\extensions\DreamArtist\scripts\dream_artist\cptuning.py", line 413, in train_embedding
    x_samples_ddim = shared.sd_model.decode_first_stage.__wrapped__(shared.sd_model, output[2])  # forward with grad
  File "D:\stable-diffusion-webui\repositories\stable-diffusion\ldm\models\diffusion\ddpm.py", line 763, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion\ldm\models\autoencoder.py", line 331, in decode
    z = self.post_quant_conv(z)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same
```

**Comment by CodeExplode** [comment]
This happens for me if I select 'Train with reconstruction', it also seems to break regular textual inversion permanently though I only noticed that once and haven't tried again.

To fix it, I had to:

1) Replace /modules/ui.py with the original, since this extension makes minor changes to the file and then it can't work anymore without the extension present, which is a big problem.

2) Remove the DreamArtist extension folder (not just disable it).

3) Restart the ui.

4) Then with the ui running, redownload or move the DreamArtist folder back into extensions.

5) Then with the ui still open, use the refresh button in the extensions tab.

6) Ensure the extension is checked to be enabled

7) Close and restart the web-ui completely

It should work again, and make sure never to click 'Train with reconstruction'

If you just want to remove the extension permanently, you just need to do 1 & 2.

**Comment by 7eu7d7** [comment]
Train with reconstruction requires more than 8G VRAM, it should be possible to train with lower VRAM without adding the ```--no-half-vae``` command, make all tensors use fp16.

**Comment by PascalTemel** [comment]
> Train with reconstruction requires more than 8G VRAM, it should be possible to train with lower VRAM without adding the `--no-half-vae` command, make all tensors use fp16.

I'm getting the same error with 24gb VRAM (rtx 3090)

**Comment by 7eu7d7** [comment]
> > Train with reconstruction requires more than 8G VRAM, it should be possible to train with lower VRAM without adding the `--no-half-vae` command, make all tensors use fp16.
> 
> I'm getting the same error with 24gb VRAM (rtx 3090)

Running in a large VRAM should not appear ```torch.cuda.HalfTensor```, there are any additional parameters added to save  VRAM?

**Comment by IdiotSandwichTheThird** [comment]
I'm running
`--listen --enable-insecure-extension-access --ckpt-dir "F:\Stable-diffusion" --no-half --precision full --no-half-vae`
with the same issue.

**Comment by PascalTemel** [comment]
> > > Train with reconstruction requires more than 8G VRAM, it should be possible to train with lower VRAM without adding the `--no-half-vae` command, make all tensors use fp16.
> > 
> > 
> > I'm getting the same error with 24gb VRAM (rtx 3090)
> 
> Running in a large VRAM should not appear `torch.cuda.HalfTensor`, there are any additional parameters added to save VRAM?

set COMMANDLINE_ARGS=--xformers --no-half --precision full --deepdanbooru --listen

**Comment by IdiotSandwichTheThird** [comment]
> > > > Train with reconstruction requires more than 8G VRAM, it should be possible to train with lower VRAM without adding the `--no-half-vae` command, make all tensors use fp16.
> > > 
> > > 
> > > I'm getting the same error with 24gb VRAM (rtx 3090)
> > 
> > 
> > Running in a large VRAM should not appear `torch.cuda.HalfTensor`, there are any additional parameters added to save VRAM?
> 
> set COMMANDLINE_ARGS=--xformers --no-half --precision full --deepdanbooru --listen

even with that, it still errors.
`RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same`

**Comment by 7eu7d7** [comment]
> > > > > Train with reconstruction requires more than 8G VRAM, it should be possible to train with lower VRAM without adding the `--no-half-vae` command, make all tensors use fp16.
> > > > 
> > > > 
> > > > I'm getting the same error with 24gb VRAM (rtx 3090)
> > > 
> > > 
> > > Running in a large VRAM should not appear `torch.cuda.HalfTensor`, there are any additional parameters added to save VRAM?
> > 
> > 
> > set COMMANDLINE_ARGS=--xformers --no-half --precision full --deepdanbooru --listen
> 
> even with that, it still errors. `RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same`

Weird bug, I can't reproduce it on my device. Is there a full command?

**Comment by Narazaka** [comment]
same issue happens for me @RTX3090

**Comment by 7eu7d7** [comment]
I tried to fix this bug in the new version, but since I can't reproduce it, I don't know if it's solved.

**Comment by Narazaka** [comment]
it seems to be fixed

**Comment by PascalTemel** [comment]
I'm trying to test it but keep getting other errors for now, I'll let you know as soon as I can if it works for me too.
Thank you for the hard work @7eu7d7!

**Comment by IdiotSandwichTheThird** [comment]
Using it with --xformers --no-half --precision full errors out of memory on 3090.
With just --xformers using 22207MiB / 24576MiB, working so far.

**Comment by PascalTemel** [comment]
![image](https://user-images.githubusercontent.com/13536271/201501566-e4de2249-2bc1-4035-98f6-a6a5fa5b387d.png)

Same OOM error as the previous commenter (if I can get through the other error)

**Comment by 7eu7d7** [comment]
> ![image](https://user-images.githubusercontent.com/13536271/201501566-e4de2249-2bc1-4035-98f6-a6a5fa5b387d.png)
> 
> Same OOM error as the previous commenter (if I can get through the other error)

Try to reduce the resolution of the image for training.

**Comment by PascalTemel** [comment]
> Try to reduce the resolution of the image for training. Good results can also be produced without adding reconstruction losses.
It works with 384x384 - do I really have to stick with that?

**Comment by IdiotSandwichTheThird** [comment]
> > Try to reduce the resolution of the image for training. Good results can also be produced without adding reconstruction losses.
> 
> It works with 384x384 - do I really have to stick with that?

It's either that or remove --no-half --precision full from the commands, it works at 512x512 with that.
