### ISSUE TITLE
Error loading script: dream_artist_main.py

### ISSUE THREAD

**Issue by Swift311** [7eu7d7/DreamArtist-sd-webui-extension#10]
Error loading script: dream_artist_main.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "D:\stable-diffusion-webui\scripts\dream_artist_main.py", line 135, in <module>
    script_callbacks.on_ui_train_tabs(on_ui_train_tabs)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_ui_train_tabs'

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\launch.py", line 252, in <module>
    start()
  File "D:\stable-diffusion-webui\launch.py", line 247, in start
    webui.webui()
  File "D:\stable-diffusion-webui\webui.py", line 149, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call)
  File "D:\stable-diffusion-webui\modules\ui.py", line 1285, in create_ui
    if hasattr(params, "dream_artist_trigger"): params.dream_artist_trigger()
NameError: name 'params' is not defined

**Comment by 7eu7d7** [comment]
Try to update webui.

**Comment by theburning** [comment]
Also having this problem, web-ui is up to date. Is there an unmentioned requirement?

**Comment by sw882882** [comment]
> Also having this problem, web-ui is up to date. Is there an unmentioned requirement? Extra fun: this broke my installation. Removed the DreamArtist folder and now SD won't launch. Thanks, I hate it.

git stash && git pull
 should fix it
its because the extension is changing the main ui.py, no idea why it does it, it should be doing it in a seperate tab or pushed to auto111. I really don't think this is the correct way, no offense to the author.

**Comment by 7eu7d7** [comment]
> > Also having this problem, web-ui is up to date. Is there an unmentioned requirement? Extra fun: this broke my installation. Removed the DreamArtist folder and now SD won't launch. Thanks, I hate it.
> 
> git stash && git pull should fix it its because the extension is changing the main ui.py, no idea why it does it, it should be doing it in a seperate tab or pushed to auto111. I really don't think this is the correct way, no offense to the author.

New verison have fix it.
