### ISSUE TITLE
请问训练时是需要使用启用EMA权重的模型吗？

### ISSUE THREAD

**Issue by kou201** [7eu7d7/DreamArtist-sd-webui-extension#15]
比如说，ND的final（925997e9）模型是latest（e68e1fc）仅剩EMA权重的修剪版，那么是否意味着我可以直接使用final模型进行训练而不必加载latest模型的config文件来启用EMA权重？

还有一个问题就是any3.0的原版模型是全量模型吗？该怎么确定一个模型是否有启用ema权重呢？

**Comment by 7eu7d7** [comment]
7G的是带ema的，4G的不带

**Comment by kou201** [comment]
> 7G的是带ema的，4G的不带
 也就是说 这篇文章（https://www.bilibili.com/read/cv19099066）是有谬误的？有点晕了。

EMA相关内容节选：
本人求知的心非常强烈，于是我就继续在外面冲浪寻求答案，然后我在某个地方看到了这样的说法。以下是原文

I have some comments regarding this. The TL;DR is that using the full model with EMA is completely unnecessary, you will get the exact same results with the pruned model. And the pruned model will use significantly less VRAM.

Now for the more detailed explanation:

One important thing that a lot of people don't seem to be aware of is that running a full model with EMA enabled is equivalent to running a pruned model, inference wise.

This is due to the fact that the pruning script removes all Non-Ema weights and only retains the EMA weights in the model. A lot of people (even very knowledgably people) gets this the wrong way around. They think the pruned files remove the EMA weights, which is not the case.

大概意思(机翻)就是说：

您没有必要用①带有EMA权重的②完整模型，您将获得与③修剪模型完全相同的结果。修剪后的模型将使用更少的 VRAM。

很多人似乎没有意识到的一件重要的事情是，在启用 ①EMA 的情况下运行②完整模型等同于运行③修剪模型，这是明智的推理。

这是因为③修剪模型删除了所有非EMA权重，仅保留模型中的EMA权重。很多人（甚至是知识渊博的人）都搞错了。他们认为修剪后的文件会删除EMA权重，但事实并非如此。

（注：①是否启用EMA权重在config文件里，若是7G的Latest模型载入了它给的config则就是启用了EMA权重

②完整模型指的是animefull-latest（7G的Latest模型）

③修剪模型指的是animefull-final-pruned（4G的Final模型））

再简单点说就是：①+②=③ 

------------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/55701610/201822561-fdc4ea9f-612c-4461-8393-2dcb8839c57e.png)

_(:з」∠)_还有这个错误似乎是在提示词模板同时存在[filewords]和[name]的时候就会百分百触发。我尝试用仅有[filewords]的txt模板训练出来的效果很烂。

**Comment by kou201** [comment]
> 7G的是带ema的，4G的不带

突发奇想分析了一下之前丢一边的yaml文件，4G模型使用yaml硬加载ema权重出图会直接花屏……您的结论应该才是正确的。

我现在有个问题就是：7G模型似乎在不加载yaml文件的情况下是不会启用ema权重的（后台没有相关提示，固定参数和SEED出图也有差别），这是否意味着需要在加载yaml文件启用ema权重的情况下再进行训练？还是说训练的时候会自行调用ema权重进行训练？
