### ISSUE TITLE
AttributeError: 'UiTrainTabParams' object has no attribute 'dream_artist_trigger'

### ISSUE THREAD

**Issue by Darkflo264** [7eu7d7/DreamArtist-sd-webui-extension#17]
Hello!
Since the pull of the latest update of your repo the webui-user.bat is crashing when i am trying to start it with the error copied to the end of this text. 
Sadly i was not able to train anything successful with your extension yet. Everything seems to be worse then without it.

Could you include the black and white dog´s example files to your downloadable embeddings, please? I would like to try with him and compare.  Indeed, it is my dog and his name is Timmy :)
Thank you very much in advance!!

Here´s the error i get when launching the .bat file:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\AI-Painting\01_stable-diffusion-webui\launch.py:256 in <module>                               │
│                                                                                                  │
│   253                                                                                            │
│   254 if __name__ == "__main__":                                                                 │
│   255 │   prepare_enviroment()                                                                   │
│ ❱ 256 │   start()                                                                                │
│   257                                                                                            │
│                                                                                                  │
│ D:\AI-Painting\01_stable-diffusion-webui\launch.py:251 in start                                  │
│                                                                                                  │
│   248 │   if '--nowebui' in sys.argv:                                                            │
│   249 │   │   webui.api_only()                                                                   │
│   250 │   else:                                                                                  │
│ ❱ 251 │   │   webui.webui()                                                                      │
│   252                                                                                            │
│   253                                                                                            │
│   254 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ D:\AI-Painting\01_stable-diffusion-webui\webui.py:149 in webui                                   │
│                                                                                                  │
│   146 │   initialize()                                                                           │
│   147 │                                                                                          │
│   148 │   while 1:                                                                               │
│ ❱ 149 │   │   demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call)             │
│   150 │   │                                                                                      │
│   151 │   │   app, local_url, share_url = demo.launch(                                           │
│   152 │   │   │   share=cmd_opts.share,                                                          │
│                                                                                                  │
│ D:\AI-Painting\01_stable-diffusion-webui\modules\ui.py:1311 in create_ui                         │
│                                                                                                  │
│   1308 │   │   │   │   shared.ti_outcome = ti_outcome                                            │
│   1309 │   │   │   │   setup_progressbar(progressbar, ti_preview, 'ti', textinfo=ti_progress)    │
│   1310 │   │                                                                                     │
│ ❱ 1311 │   │   params.dream_artist_trigger()                                                     │
│   1312 │   │   create_embedding.click(                                                           │
│   1313 │   │   │   fn=modules.textual_inversion.ui.create_embedding,                             │
│   1314 │   │   │   inputs=[                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'UiTrainTabParams' object has no attribute 'dream_artist_trigger'

**Comment by sotokisehiro** [comment]
Please run the following command and let me know the result.

`$ git status`

**Comment by sotokisehiro** [comment]
If modules/ui.py has changed,
Execute the following command to fix it.
`git checkout modules/ui.py`

**Comment by 7eu7d7** [comment]
The new version fix this bug.
