### ISSUE TITLE
web-ui cannot start without extension present

### ISSUE THREAD

**Issue by CodeExplode** [7eu7d7/DreamArtist-sd-webui-extension#2]
Due to the changes made in ui.py, disabling the extension means that the web-ui will no longer start.

It may be a bug on Automatic's part, but the hooks seem to get added back in even if the extension is disabled (though I haven't re-tested that yet).

So currently it requires replacing ui.py and deleting the extension before opening the web ui, to allow it to work again.

**Comment by H4Z33** [comment]
It's not an error on A1111, but maybe he needs to start limiting what the extensions can do, you have to go into ui.py and remove the edits that the extension does when you install it via git, or just delete iu.py and do a git pull on the main of A1111/webui.

**Comment by 7eu7d7** [comment]
The new version fixes this issue.

You can directly replace ```params.dream_artist_trigger()``` with ```if hasattr(params, "dream_artist_trigger"): params.dream_artist_trigger()``` in modules/ui.py to fix it.

**Comment by jdack41** [comment]
It seems somewhat wild to jump over the scope of the extension and rewrite the original ui.py.
I think it would be better to separate them as separate tabs if possible, or if it is difficult, to submit a PR in the automatic1111 body instead of in the extension.
