### ISSUE TITLE
No module called launch - Colab Error

### ISSUE THREAD

**Issue by mediocreatmybest** [7eu7d7/DreamArtist-sd-webui-extension#22]
Hi, went to run this via colab, normally I don't have any issues with the colab running. 
Installing the extension gives the following error:

`Connected
Error running install.py for extension /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension.
Command: "/usr/bin/python3" "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/install.py", line 1, in <module>
    import launch
ModuleNotFoundError: No module named 'launch'`

If I restart the webui, it does look like it loads, but I'm unable to train as it throws an error or runs out of memory. 
The colab has 16GB of vRAM.

Thanks!

**Comment by mediocreatmybest** [comment]
After manually checking the Scikit_learn is installed and imports correctly, re tried training. 
Get this error on the interface. 

AttributeError: 'NoneType' object has no attribute 'detach'

**Comment by 7eu7d7** [comment]
install.py is executed automatically by webui, just put this project into extensions folder and start webui.

**Comment by 7eu7d7** [comment]
> After manually checking the Scikit_learn is installed and imports correctly, re tried training. Get this error on the interface.
> 
> AttributeError: 'NoneType' object has no attribute 'detach'

xfromers need to be turn off

**Comment by 7eu7d7** [comment]
> If I switch on reconstruction I run out of memory on the 16GB VRAM GPU instantly.
> How much memory does it require?

Train with reconstruction using 512x512 images needs at least 24GB VRAM. If your computational resources are not rich, you can leave it out and will not lose much performance.
