### ISSUE TITLE
Removing DreamArtists requires you to reinstall stable diffusion

### ISSUE THREAD

**Issue by KingPendragoon** [7eu7d7/DreamArtist-sd-webui-extension#23]
basically the title but the act of disabling dreamArtist causes the entire stable diffusion to become unusable unless you delete it all and reinstall it.

**Comment by tsukimiya** [comment]
In older versions, modules/ui.py was rewritten, so if you delete DreamArtist, you will need to revert modules/ui.py to its original state yourself.
For example, this is how.
```
git checkout modules/ui.py
```
This does not occur on the current latest master branch.

**Comment by 7eu7d7** [comment]
This is fixed in the new verison.
