### ISSUE TITLE
Batch size doesn't work

### ISSUE THREAD

**Issue by MalumaDev** [7eu7d7/DreamArtist-sd-webui-extension#24]
Batch size doesn't work:
`RuntimeError: einsum(): operands do not broadcast with remapped shapes [original->remapped]: [16, 4096, 40]->[16, 4096, 1, 40] [32, 77, 40]->[32, 1, 77, 40]`

**Comment by Yakumounr** [comment]
Batch size was working for me yesterday, increasing it showed a considerable increase in vram usage too.
After an update that installed earlier today I get similar errors to MalumaDev and Batch Size 1 is the only setting that allows for training, but the vram usage is now similar to using batch size 5 or 6 previously.
