### ISSUE TITLE
Embeddings not loading

### ISSUE THREAD

**Issue by alelordelo** [7eu7d7/DreamArtist-sd-webui-extension#26]
Hi @7eu7d7 , thanks for this awesome model! 

I created an embed:
<img width="1430" alt="Screenshot 2022-11-18 at 17 21 37" src="https://user-images.githubusercontent.com/17708751/202752770-88ac2b0a-d380-42f9-8bf3-89e6af6b3a1a.png">

But when I try to load, it doesn't show up.
<img width="1439" alt="Screenshot 2022-11-18 at 17 23 17" src="https://user-images.githubusercontent.com/17708751/202753223-cf2240a7-a764-4f9f-9a51-3d540955381b.png">

Did I do anything wrong?

Cheers from Stockholm

**Comment by 7eu7d7** [comment]
Try to update the webui.

**Comment by learnifysean** [comment]
try with `--disable-safe-unpickle`
