### ISSUE TITLE
Simplified Chinese localization 简体中文翻译问题

### ISSUE THREAD

**Issue by batvbs** [7eu7d7/DreamArtist-sd-webui-extension#28]
你好，我是[webui简体中文语言包](https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN)的协作者之一。

目前我们对DreamArtist的翻译选择存在困惑，想问问你对此有没有什么意见？

梦作家？梦想艺术家？梦想画家？

![22](https://user-images.githubusercontent.com/60730393/202854229-284c6608-5d30-4f9e-84da-27cb11bf7b34.png)

**Comment by 7eu7d7** [comment]
翻译成 ```梦想艺术家``` 比较合适
