### ISSUE TITLE
和dreambooth的区别

### ISSUE THREAD

**Issue by nick008a** [7eu7d7/DreamArtist-sd-webui-extension#29]
想请教一下，相比现有的dreambooth，这版主要的改进是什么呢？为什么只需要一张图就够了呢？

**Comment by 7eu7d7** [comment]
dreambooth要fine-tuning整个模型，训练成本很高，而且非常容易过拟合。DreamArtist只学一正一负一对embedding，可学习参数很小<50kb。但效果在很多情况可以超过DB，只要一张图也不会过拟合。论文最近会公开，细节可以后面看论文
