### ISSUE TITLE
Can you feed many images when training an embedding?

### ISSUE THREAD

**Issue by off99555** [7eu7d7/DreamArtist-sd-webui-extension#43]
I saw this text while training an embedding for the shuimo embedding.
I named the embedding `test1` and give it access to images folder with only one image inside it (`shuimo.jpg`).
![image](https://user-images.githubusercontent.com/15215732/209327200-5df0afad-5f86-49b4-95cd-47b3f7830e2c.png)
![shuimo](https://user-images.githubusercontent.com/15215732/209327264-b0e26e95-bf6c-491b-b323-ee6ff4861453.jpg)

So I speculated that you can feed more than one image to train an embedding.
Is it true that I can feed more images to training process and would that theoretically improve performance?

**Comment by kenedos** [comment]
I tried with 3 images of 3 different characters drawn by same artist, but did not achieve any success. After running over 12000 steps, the model would just keep cycling between trying to represent each image in dataset in a very blurry way.

**Comment by IrisRainbowNeko** [comment]
Multiple images depicting the same object or style is possible to improve the performance. If you think the result is not good enough, you can try the newly released and improved version of DreamArtist++. https://github.com/7eu7d7/HCP-Diffusion
