### ISSUE TITLE
About subject textual inversion

### ISSUE THREAD

**Issue by XinWangg** [7eu7d7/DreamArtist-sd-webui-extension#48]
你好~
当我使用dreamart提出的正负embedding训练方法对风格图片进行训练的时候，能够正常得到对应的风格embedding。
但是当我使用具体实物图片进行subject训练的时候，无法得到对应的正确embedding，想咨询下是哪里出了问题~
我的训练参数：
    'train_args': ['real-sship', '0.003', 1, '/path/to/stable-diffusion-webui/textual_inversion_traindata',
    'dream_artist', 512, 512, 3000, 100, 100, '/path/to/stable-diffusion-webui/textual_inversion_templates/subject.txt',
    True, False, '', '', 20, 0, 7, -1.0, 512, 512,'5.0','',True, True,1,1,0.97,25.0,0.97,25.0,0.9,0.999,False,1,False,'0.000005']
    }
正常使用stable diffusion代码训练embedding能够得到正常结果。

**Comment by IrisRainbowNeko** [comment]
训练物体使用cfg=3.0比较好
