### ISSUE TITLE
Prompt generation bug with [filewords]

### ISSUE THREAD

**Issue by mykeehu** [7eu7d7/DreamArtist-sd-webui-extension#59]
Why use the filenames in the folder to generate for filewords? This is not good!

Currently there are 4 files:
- img1.png <- train image
- img1.txt <- filewords
- img1_att.png <- Attention map before process
- img1_att_proc.png <- Attention map

And use the names of these when generating the prompt, with variations, e.g. a _photo of ohwx, img1_att_proc_ or _img1_att, photo of ohwx_

The problem is that it uses the same buggy prompt for training and sample prompts.

Then you should use the keyword: _a photo of ohwx, (keywords from txt)_ or _(keywords from txt), a photo of ohwx_

If there is no txt file and the filewords template is selected by mistake, then it should be empty, but not the file names.

![image](https://user-images.githubusercontent.com/6390413/213632509-5b30c8b2-59a2-4d72-9bd6-cc2a477d3938.png)

**Comment by IrisRainbowNeko** [comment]
You show rename the "img1_att_proc.png" to "img1_att.png"
