### ISSUE TITLE
Can't get a dynamic cfg to work

### ISSUE THREAD

**Issue by RainehDaze** [7eu7d7/DreamArtist-sd-webui-extension#61]
I'm not sure how you're supposed to specify a dynamic cfg value--trying it as presented on the main page or suggested in the training tab--e.g. 1.0-3.5:cos, or (1.0-3.5:cos)--only produces a ValueError as the contents of the box cannot be converted from a string to a float.

**Comment by jjtolton** [comment]
This is correct, you cannot. (I just went through the code recently for a different PR).  Can you help me understand what this does and maybe I can patch it in?

**Comment by RainehDaze** [comment]
I assume it's meant to vary between the two cfgs over the course of training, with no specification being a linear variance. Unfortunately, the main page doesn't clarify whether this is meant to return to the starting point or... much of anything.

**Comment by IrisRainbowNeko** [comment]
It works fine in the latest version
