### ISSUE TITLE
额点开始训练没反应，不知道为什么

### ISSUE THREAD

**Issue by Sincejunly** [7eu7d7/DreamArtist-sd-webui-extension#69]
![image](https://user-images.githubusercontent.com/96775034/229303113-f9f186e7-1f4e-4816-aecf-65ad1b531507.png)
点击无反应，为什么？

**Comment by Sincejunly** [comment]
Embdding已经设置了

**Comment by lxy2017** [comment]
我也遇到一样的问题，点击没反应

**Comment by 7eu7d7** [comment]
已经修复了
