### ISSUE TITLE
8G显存无法训练？

### ISSUE THREAD

**Issue by NaughtDZ** [7eu7d7/DreamArtist-sd-webui-extension#71]
已开启xform，可以训练lora，可以训练hypernetwork，可以训练普通的embbeding，就是一跑dreamartist就爆显存。

**Comment by 7eu7d7** [comment]
可以减少batch size或者图像尺寸

**Comment by NaughtDZ** [comment]
> 可以减少batch size或者图像尺寸

都减到384*384了，再减训练的就是马赛克了朋友。
真的不能在训练中添加一些优化器或者 别的啥降低显存使用量？
