### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by dikasterion** [7eu7d7/DreamArtist-sd-webui-extension#8]
I'm using RTX3080 10GB.
tried DreamArtist but the console says OOM error message...
so how much vram do I need?

tried uncheck 'Train with reconstruction'

the error message is like below
`
Preparing dataset...
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.79s/it]
  0%|                                                                                       | 0/100000 [00:01<?, ?it/s]
Applying xformers cross attention optimization.
Error completing request
Arguments: ('test1', '0.005', 1, 'D:\\stable-diffusion-webui\\image_source\\girl', 'textual_inversion', 512, 512, 100000, 500, 500, 'D:\\stable-diffusion-webui\\textual_inversion_templates\\style_filewords.txt', True, False, '', '', 20, 0, 7, -1.0, 512, 512, 5.0, '', True, False, 1, 1) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\DreamArtist\scripts\dream_artist\ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "D:\stable-diffusion-webui\extensions\DreamArtist\scripts\dream_artist\cptuning.py", line 430, in train_embedding
    loss.backward()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion\ldm\modules\diffusionmodules\util.py", line 139, in backward
    input_grads = torch.autograd.grad(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 276, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 10.00 GiB total capacity; 6.31 GiB already allocated; 0 bytes free; 7.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

(btw, thanks for this wonderful project)

**Comment by Razgrits** [comment]
Not entirely related but since I got this extension on webui I've had memory issues outside of training. I can no longer generate anything beyond 640x640 when before I could generate 1024x1024 and my it/s have dropped to less than half. I've been trying for almost a day to revert things back to normal but nothing I've done has worked.
Reinstalling x-formers, activating --medvram(when I didn't have to before even if I am on a 2060), nothing fixes it.

**Comment by Razunter** [comment]
Training without issues on RTX3080 10GB (no reconstruction), but results and speed isn't any better than default TI.

**Comment by 7eu7d7** [comment]
> Training without issues on RTX3080 10GB (no reconstruction), but results and speed isn't any better than default TI. 320x320 works with reconstruction, training with multiple images, don't see any improvement to a default TI. Haven't tried single image though.

You can refer to the recommended parameter settings in https://github.com/7eu7d7/DreamArtist-sd-webui-extension#pre-trained-embeddings. There are differences in the parameter settings between DreamArtist and TI.

**Comment by dikasterion** [comment]
> Training without issues on RTX3080 10GB (no reconstruction), but results and speed isn't any better than default TI.
320x320 works with reconstruction, training with multiple images, don't see any improvement to a default TI. Haven't tried single image though.

mine is working with 320x320, not like 512x512. thanks for sharing your case
