### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper__convolution_backward)

### ISSUE THREAD

**Issue by Raz0rStorm** [7eu7d7/DreamArtist-sd-webui-extension#9]
Trying to train locally,but got error
Preparing dataset...
100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:02<00:00,  5.10it/s]
use convnext discriminator
  0%|                                                                                       | 0/100000 [00:02<?, ?it/s]
Error completing request
Arguments: ('mmkex', '0.005', 1, 'D:\\Grabber\\mmkapt', 'textual_inversion', 128, 128, 100000, 500, 500, 'D:\\stable-diffusion-webui\\textual_inversion_templates\\style_filewords.txt', True, False, '', '', 20, 0, 7, -1.0, 512, 512, 5.0, 'D:\\stable-diffusion-webui\\models\\convnext\\checkpoint-best_t5.pth', True, False, 1, 1) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "D:\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\cptuning.py", line 430, in train_embedding
    loss.backward()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper__convolution_backward)

**Comment by Raz0rStorm** [comment]
I changed the resolution from 128 to 512 and it seemed to work?

**Comment by Jarfeh** [comment]
This is still a problem. Resolution is set to 512x512 and is still happening.

**Comment by Raz0rStorm** [comment]
> This is still a problem. Resolution is set to 512x512 and is still happening.

Yea reopening it, in my case any resolution below 384 will lead to this error

**Comment by mykeehu** [comment]
[This might be the solution](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4271) to the bug, but Automatic has not yet allowed it.

**Comment by Raz0rStorm** [comment]
> [This might be the solution](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4271) to the bug, but Automatic has not yet allowed it.

sadge, hope they soon merge it

**Comment by mykeehu** [comment]
@Raz0rStorm until they fix it, I made a copy of the current file (so that there is no problem when updating) and manually modified the file based on the code there. When there was an update, I swapped the two files, refreshed the SD, then swapped back to the modified one. For the time being I had no better idea, I'm waiting for my own, so I don't have to do any tricks.

**Comment by 7eu7d7** [comment]
The new version forces the VAE to load in training, which may fix the issue.
